include:
  - '/.ci/gitlab/publish.yml'
#   - '/.ci/gitlab/benchmark.yml'

stages:
  - test
  - pack
  - pack-test
  - publish

# Triggers child pipelines that runs tests for various GHC and Cabal versions.
# Should be replaced by matrix builds in the future, but currently blocking on:
# https://gitlab.com/gitlab-org/gitlab/-/issues/270957
.common:
  stage: test
  trigger:
    include: .ci/gitlab/test.yml
    strategy: depend

tests-8.4:
  extends: .common
  variables:
    GHC_VERSION: 8.4.4
    CABAL_VERSION: 2.4.1.0

tests-8.6:
  extends: .common
  variables:
    GHC_VERSION: 8.6.5
    CABAL_VERSION: 3.0.0.0
    MULTIPLE_HIDDEN: "no"

tests-8.8:
  extends: .common
  variables:
    GHC_VERSION: 8.8.4
    CABAL_VERSION: 3.2.0.0

tests-8.10:
  extends: .common
  variables:
    GHC_VERSION: 8.10.3
    CABAL_VERSION: 3.2.0.0

# # Run benchmarks for isclashfastyet.com
# benchmark-8.10.2:
#   extends: .benchmark

# "Publish" a release candidate
hackage-release-candidate:
  extends: .hackage

  variables:
    HACKAGE_RELEASE: "no"

  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "trigger"

# Release new version of Clash to Hackage
hackage-release:
  extends: .hackage

  variables:
    HACKAGE_RELEASE: "yes"

  rules:
    - if: '$CI_COMMIT_TAG != null' # tags

# Publish a release candidate (beta/edge) to snapcraft.io/clash
snap-beta-or-edge:
  extends: .snap
  variables:
    RELEASE_CHANNEL: beta_or_edge
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "trigger"

# Publish a new version to stable channel on snapcraft.io/clash
snap-stable:
  extends: .snap
  variables:
    RELEASE_CHANNEL: stable
  rules:
    - if: '$CI_COMMIT_TAG != null' # tags
