resolver: nightly-2016-08-06

packages:
- 'clash-prelude'
- 'clash-lib'
- 'clash-verilog'
- 'clash-systemverilog'
- 'clash-vhdl'
- 'clash-ghc'
- 'testsuite'
- 'ghc-typelits-extra'
- 'ghc-typelits-natnormalise'
