resolver: nightly-2016-07-19

packages:
- .
- location:
    git: https://github.com/clash-lang/ghc-typelits-knownnat.git
    commit: f8d2ed35f137b86aa973780f294086104e812ef0
  extra-dep: true

flags:
  clash-prelude:
    doclinks: true
